### Exploring YouTube videos's data set:
##### - calculate mean\min\max views for each category using groupby
##### - calculate tags for each video
##### - add an additional field 'title_category' using descripton stored in **category_id.csv**
##### - use **pivot_table** to calculate views for some video channels by category titles.

In [1]:
import pandas as pd

In [33]:
yt_df = pd.read_csv('data/youtube_videos.csv')

In [3]:
yt_df.head()

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description
0,Jw1Y-zhQURU,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26.0,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515.0,55681.0,10247.0,9479.0,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24.0,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632.0,25561.0,2294.0,2757.0,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10.0,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579.0,787420.0,43420.0,125882.0,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17.0,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833.0,193.0,12.0,37.0,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25.0,2017-11-13T01:45:13.000Z,[none],9815.0,30.0,2.0,30.0,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,Dashcam captures truck's near miss with child ...

In [4]:
# - calculate mean\min\max views for each category using groupby
yt_df.groupby('category_id',sort=False).agg({'views':['mean', 'min','max']})

                    views
                     mean       min          max
category_id
26.0         6.173004e+05    1505.0    8721841.0
24.0         3.264608e+06    2650.0  169884583.0
10.0         1.244444e+07    2152.0  424538912.0
17.0         1.752352e+06    1930.0   22975455.0
25.0         1.150311e+06     851.0   18994966.0
22.0         1.966606e+06    1184.0   62338362.0
23.0         2.167430e+06   10676.0   43460605.0
28.0         3.168703e+06   38353.0   21530325.0
15.0         1.013709e+06   25232.0    6416920.0
27.0         9.721894e+05    8851.0   11240174.0
1.0          3.245133e+06    2441.0   42560014.0
20.0         9.768566e+05    7350.0   18158133.0
2.0          1.487392e+06    1858.0    5362914.0
19.0         1.383177e+06    3254.0    6362355.0
29.0         3.919981e+06   19270.0   26703269.0
43.0         1.429164e+06  876996.0    1709880.0

In [18]:
# - calculate tags for each video
yt_df.groupby('video_id')['tags'].apply('|'.join).apply(lambda row: len(set(str(row).split("|"))))

video_id
--uXQQ0h-yQ     5
-3VBPAZPTQI    13
-43MBOJnVks    29
-5WBCrazSfg    30
-5aaJJQFvOg     8
               ..
zwEn-ambXLw    13
zwrlJwed2mQ    13
zxGg8QqWrRQ    32
zxjv0lo8bU8    11
zxwfDlhJIpw    34
Name: tags, Length: 3272, dtype: int64

In [32]:
# - add an additional field 'title_category' using descripton stored in **category_id.csv**
categories_df = pd.read_csv('data/category_id.csv')

In [34]:
yt_df = pd.merge(yt_df, categories_df, on='category_id', suffixes=(None,'_category'))

In [35]:
yt_df.head()

,video_id,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,description,title_category
0,Jw1Y-zhQURU,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26.0,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515.0,55681.0,10247.0,9479.0,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,Click here to continue the story and make your...,Howto & Style
1,3s1rvMFUweQ,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24.0,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632.0,25561.0,2294.0,2757.0,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,Musical guest Taylor Swift performs …Ready for...,Entertainment
2,n1WpP7iowLc,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10.0,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579.0,787420.0,43420.0,125882.0,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,Eminem's new track Walk on Water ft. Beyoncé i...,Music
3,PUTEiSjKwJU,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17.0,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833.0,193.0,12.0,37.0,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,Salford drew 4-4 against the Class of 92 and F...,Sports
4,rHwDegptbI4,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25.0,2017-11-13T01:45:13.000Z,[none],9815.0,30.0,2.0,30.0,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,Dashcam captures truck's near miss with child ...,News & Politics

In [ ]:
# - use **pivot_table** to calculate views for some video channels by category titles.
yt_df[(yt_df['channel_title']=='Bruno Mars')|
      (yt_df['channel_title']=='BBC News')|
      (yt_df['channel_title']=='Jimmy Kimmel Live')].pivot_table(index='channel_title', 
                                                                 columns='title_category',
                                                                 values='views', 
                                                                 aggfunc='sum',
                                                                 fill_value=0,
                                                                 dropna=True)

title_category,Comedy,Entertainment,Film & Animation,Music,News & Politics,Pets & Animals,Science & Technology
channel_title,,,,,,,
BBC News,0.0,0.0,3029810.0,0.0,9531719.0,13590561.0,1250438.0
Bruno Mars,0.0,0.0,0.0,687606646.0,0.0,0.0,0.0
Jimmy Kimmel Live,252950561.0,144506232.0,0.0,778276.0,0.0,0.0,0.0